package com.company;
import java.security.SecureRandom;
import java.util.Scanner;
import java.lang.Math;
import java.util.Random;
    //allows for a object that stores 2 integers generated by secure random
class genInt {
    public int num1;
    public int num2;
    //constuctor
    public genInt () {
        num1 = 0;
        num2 = 0;
    }
    // sets only the positive values of secure random
    public void setInt (SecureRandom random, int difficulty) {
        if (difficulty == 1) {
            num1 = Math.abs(random.nextInt() % 9) + 1;
            num2 = Math.abs(random.nextInt() % 9) + 1;
        }
        else if (difficulty == 2) {
            num1 = Math.abs(random.nextInt() % 90) + 10;
            num2 = Math.abs(random.nextInt() % 90) + 10;
        }
        else if (difficulty == 3) {
            num1 = Math.abs(random.nextInt() % 900) + 100;
            num2 = Math.abs(random.nextInt() % 900) + 100;
        }
        else if (difficulty == 4) {
            num1 = Math.abs(random.nextInt() % 9000) + 1000;
            num2 = Math.abs(random.nextInt() % 9000) + 1000;
        }
    }

}


public class Main {

    //method that makes a problem
    public static int generateProb (int num1, int num2, Random randomInt, int problemType) {
        if (problemType == 5) {
            problemType = randomInt.nextInt(4) + 1;
        }
        if (problemType == 1) {
            System.out.printf("How much is %d plus %d?\n", num1, num2);
        }
        if (problemType == 2) {
            System.out.printf("How much is %d times %d?\n", num1, num2);
        }
        if (problemType == 3) {
            System.out.printf("How much is %d minus %d?\n", num1, num2);
        }
       if (problemType == 4) {
            System.out.printf("How much is %d divided by %d?\n", num1, num2);
        }
        return problemType;
    }

    //method that allows for difficulty selection
    public static int difficultyLevel (Scanner scnr) {
        int difficulty;
        System.out.println("Please select a difficulty level 1-4.");
        difficulty = scnr.nextInt();

        return difficulty;
    }
    //method that allows for the types of problems to be generated.
    public static int problemType (Scanner scnr) {
        int problemType;

        System.out.println("What type of problems would you like to do?");
        System.out.println("Type 1 for addition, 2 for multiplication, 3 for subtraction, 4 for division, or 5 for a mix of all.");
        problemType = scnr.nextInt();
        return problemType;
    }
    //method that prints one of four correct responses
    public static void correctResponse (Random randomInt) {
        int x = randomInt.nextInt(4);

        switch (x) {
            case (0):
                System.out.println("Very good!");
                break;
            case (1):
                System.out.println("Excellent!");
                break;
            case (2):
                System.out.println("Nice work!");
                break;
            case (3):
                System.out.println("Keep up the good work!");
                break;
        }
    }
    //method that prints one of four incorrect responses
    public static void incorrectResponse (Random randomInt) {
        int x = randomInt.nextInt(4);

        switch (x) {
            case (0):
                System.out.println("No. Please try again.");
                break;
            case (1):
                System.out.println("Wrong. Try once more.");
                break;
            case (2):
                System.out.println("Don't give up!");
                break;
            case (3):
                System.out.println("No. Keep trying.");
                break;
        }
    }
    // checks if answer is correct, returns 1 if correct, zero otherwise
    public static int checkAnswer (double ans, int num1, int num2, int problemType, Random randomInt) {
            if (problemType == 1) {
                if (ans == num1 + num2) {
                    correctResponse(randomInt);
                    return 1;
                }
                else {
                    incorrectResponse(randomInt);
                    return 0;
                }
            }
            if (problemType == 2) {
                if (ans == num1 * num2) {
                    correctResponse(randomInt);
                    return 1;
                }
                else {
                    incorrectResponse(randomInt);
                    return 0;
                }
            }
            if (problemType == 3) {
                if (ans == num1 - num2) {
                    correctResponse(randomInt);
                    return 1;
                }
                else {
                    incorrectResponse(randomInt);
                    return 0;
                }
            }
            if (problemType == 4) {
                if (Math.abs(ans - (float)num1 / num2) < 0.01) {
                    correctResponse(randomInt);
                    return 1;
                }
                else {
                    incorrectResponse(randomInt);
                    return 0;
                }
            }
            return 0;
    }

    public static void main(String[] args) {
	// write your code here
        SecureRandom random = new SecureRandom();
        Scanner scnr = new Scanner(System.in);
        Random randomInt = new Random();

        //define variables
        double ans;
        int flag = 1;
        int i;
        int problemType;
        int tracker;
        int counter;
        int difficulty;
        float average;

        //create object named numbers
        genInt numbers = new genInt();


        //set initial conditions and starts the loop
        while (flag == 1) {
            difficulty = difficultyLevel(scnr);
            problemType = problemType(scnr);
            numbers.setInt(random, difficulty);
            counter = 0;
            //generates 10 problems and checks if correct
            for (i = 0; i < 10; ++i) {
                numbers.setInt(random, difficulty);
                tracker = generateProb(numbers.num1, numbers.num2, randomInt, problemType);
                ans = scnr.nextFloat();
                counter += checkAnswer(ans, numbers.num1, numbers.num2, tracker, randomInt);
                System.out.println();
            }
            //calculates and prints the percentage correct
            average =  ((float) counter / 10) * 100;
            System.out.printf("You got %d out of 10 correct for %.2f%%\n", counter, average);
            if (average > 75) {
                System.out.println("Congradulations, you are ready to go to the next level!");
            }
            else
                System.out.println("Please ask your teacher for extra help.");
            // allows for user to reset the program
            System.out.println();
            System.out.println("Would you like to reset?");
            System.out.println("Type 1 to reset, type 2 to quit.");
            flag = scnr.nextInt();
        }
    }
}
